[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@crypto-lib/=lib/crypto-lib/",
    "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200

# IMPORTANT: Crypto library requires via_ir = false
solc = "0.8.30"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${ES_KEY}" }
base_sepolia = { key = "${ES_KEY}" }
