[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@crypto-lib/=lib/crypto-lib/"
]
optimizer = true
optimizer_runs = 5000

# Optimizer settings for size reduction
solc = "0.8.30"
# via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }
